[build]
  command = "npm install --no-audit --no-fund && npm run build"
  publish  = "dist"

# Allow external resources we need (Base44, fonts, images, etc.)
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self' https: data: blob:;
    script-src  'self' https: 'unsafe-eval';
    style-src   'self' https: 'unsafe-inline';
    img-src     'self' https: data: blob:;
    font-src    'self' https: data:;
    connect-src 'self' https: wss:;
    frame-src   'self' https:;
    base-uri    'self';
    object-src  'none';
    frame-ancestors 'self'
  """
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
